import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Original design system colors
        primary: "#2563EB",
        "primary-dark": "#1D4ED8",
        accent: "#10B981",
        "accent-orange": "#F59E0B",
        danger: "#EF4444",
        surface: "#F8FAFC",
        card: "#FFFFFF",
        "text-primary": "#0F172A",
        "text-muted": "#64748B",

        // Material Design 3 / Stitch design tokens
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "surface-tint": "#0053db",
        "on-surface": "#131b2e",
        "on-surface-variant": "#434655",
        "on-background": "#131b2e",
        background: "#faf8ff",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-primary": "#b4c5ff",
        secondary: "#712ae2",
        "secondary-container": "#8a4cfc",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-fixed-variant": "#5a00c6",
        tertiary: "#006242",
        "tertiary-container": "#007d55",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
      },
      fontFamily: {
        sans: ["var(--font-montserrat)", "sans-serif"],
        serif: ["var(--font-crimson)", "serif"],
        headline: ["var(--font-montserrat)", "sans-serif"],
        body: ["var(--font-crimson)", "serif"],
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.04)",
        "card-hover": "0 4px 12px rgba(37,99,235,0.12), 0 8px 24px rgba(0,0,0,0.08)",
        arch: "0 8px 32px rgba(19,27,46,0.06)",
      },
      borderRadius: {
        card: "16px",
        button: "10px",
        badge: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
